const { RELEASE_VERSION, BASE32_VERSION, IS_LTS } = process.env
console.log({
  RELEASE_VERSION: RELEASE_VERSION,
  BASE32_VERSION: BASE32_VERSION,
  IS_LTS: IS_LTS,
})
module.exports = {
  RELEASE_VERSION: RELEASE_VERSION ?? '6.20.0-rc.3',
  BASE32_VERSION: BASE32_VERSION ?? 'AA',
  IS_LTS: IS_LTS ?? false,
}
