#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'
require 'parallel'
require 'json'

@browsers = JSON.load(open('browsers.json'))
@parallel_limit = 1
@parallel_limit = @parallel_limit.to_i

task :cucumber do
  if ENV['BROWSER_STACK'] == 'true'
    Parallel.each(@browsers, :in_processes => @parallel_limit) do |browser|
      begin
        puts "Running with: #{browser.inspect}"
        ENV['SELENIUM_BROWSER'] = browser['browser']
        ENV['SELENIUM_VERSION'] = browser['browser_version']
        ENV['BS_AUTOMATE_OS'] = browser['os']
        ENV['BS_AUTOMATE_OS_VERSION'] = browser['os_version']

        Rake::Task[:run_features].execute()
      rescue Exception => e
        puts "Error while running task"
      end
    end
  else
    Rake::Task[:run_features].execute()
  end
end

Cucumber::Rake::Task.new(:run_features) do |t|
  t.cucumber_opts = [
    '--tags', (ENV['CUCUMBER_TAGS'] || '~none'),
    ENV['BROWSER_STACK'] == 'false' ?
      'BROWSER=${BROWSER:-chrome}' : ''
  ]
end
task :default => [:cucumber]
