export const uploadDocument = jest.fn()
export const uploadLivePhoto = jest.fn()
export const uploadSnapshot = jest.fn()
export const sendMultiframeSelfie = jest.fn()
export const uploadDocumentVideo = jest.fn()
export const uploadFaceVideo = jest.fn()
