export const objectToFormData = jest.fn().mockReturnValue(new FormData())
export const formatError = jest.fn()
export const uploadDocument = jest.fn().mockResolvedValue({})
export const uploadLiveVideo = jest.fn().mockResolvedValue({})
export const sendMultiframeSelfie = jest.fn().mockResolvedValue({})
export const uploadLivePhoto = jest.fn().mockResolvedValue({})
