export const objectToFormData = jest.fn().mockReturnValue(new FormData())
export const formatError = jest.fn()
export const uploadDocument = jest.fn()
export const uploadFacePhoto = jest.fn()
export const uploadSnapshot = jest.fn()
export const sendMultiframeSelfie = jest.fn()
export const uploadDocumentVideo = jest.fn()
export const uploadFaceVideo = jest.fn()
export const getPoASupportedCountries = jest.fn().mockResolvedValue([])
export const getApplicantConsents = jest.fn().mockResolvedValue([])
export const updateApplicantConsents = jest.fn().mockResolvedValue(undefined)
export const updateApplicantLocation = jest.fn().mockResolvedValue(undefined)

// v4 APIs
export const uploadBinaryMedia = jest.fn()
export const createV4Document = jest.fn()
