export const SOCKET_URL = 'wss://ws.onfido.com'

export const DOCUMENT_CAPTURE = 'DOCUMENT_CAPTURE'
export const FACE_CAPTURE = 'FACE_CAPTURE'

export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_WEBSOCKET_SUPPORT = 'SET_WEBSOCKET_SUPPORT'
export const SET_WEBSOCKET_ERROR = 'SET_WEBSOCKET_ERROR'
export const SET_GUM_SUPPORT = 'SET_GUM_SUPPORT'
export const SET_DOCUMENT_TYPE = 'SET_DOCUMENT_TYPE'
export const SET_CURRENT_CAPTURE = 'SET_CURRENT_CAPTURE'

export const CAPTURE_CREATE = 'CAPTURE_CREATE'
export const CAPTURE_VALIDATE = 'CAPTURE_VALIDATE'
export const CAPTURE_CONFIRM = 'CAPTURE_CONFIRM'
export const CAPTURE_DELETE = 'CAPTURE_DELETE'
