export const errors = translate => ({
  'INVALID_CAPTURE': { message: translate('errors.invalid_capture.message'), instruction: translate('errors.invalid_capture.instruction')},
  'INVALID_TYPE': { message: translate('errors.invalid_type.message'), instruction: translate('errors.invalid_type.instruction')},
  'UNSUPPORTED_FILE': { message: translate('errors.unsupported_file.message'), instruction: translate('errors.unsupported_file.instruction')},
  'INVALID_SIZE': { message: translate('errors.invalid_size.message'), instruction: translate('errors.invalid_size.instruction')},
  'NO_FACE_ERROR': { message: translate('errors.no_face.message'), instruction: translate('errors.no_face.instruction')},
  'MULTIPLE_FACES_ERROR': { message: translate('errors.multiple_faces.message'), instruction: translate('errors.multiple_faces.instruction')},
  'SERVER_ERROR': { message: translate('errors.server_error.message'), instruction: translate('errors.server_error.instruction')},
  'GLARE_DETECTED': { message: translate('errors.glare_detected.message'), instruction: translate('errors.glare_detected.instruction')},
  'SMS_FAILED': { message: translate('errors.sms_failed.message'), instruction: translate('errors.sms_failed.instruction')},
  'SMS_OVERUSE': { message: translate('errors.sms_overuse.message'), instruction: translate('errors.sms_overuse.instruction')},
  'CAMERA_NOT_WORKING': { message: translate('errors.camera_not_working.message'), instruction: translate('errors.camera_not_working.instruction')},
  'CAMERA_INACTIVE': { message: translate('errors.camera_inactive.message'), instruction: translate('errors.camera_inactive.instruction')},
  'LIVENESS_TIMEOUT': { message: translate('errors.liveness_timeout.message'), instruction: translate('errors.liveness_timeout.instruction')},
})
