export const SET_DOCUMENT_TYPE = 'SET_DOCUMENT_TYPE'

export const CAPTURE_CREATE = 'CAPTURE_CREATE'
export const CAPTURE_VALIDATE = 'CAPTURE_VALIDATE'
export const CAPTURE_CONFIRM = 'CAPTURE_CONFIRM'
export const CAPTURE_DELETE = 'CAPTURE_DELETE'

export const RESET_STORE = 'RESET_STORE'
