export const allCountriesList = [
  {
    countryCode: 'AF',
    labelKey: 'countriesList.af',
    isoAlpha3: 'AFG',
  },
  {
    countryCode: 'AL',
    labelKey: 'countriesList.al',
    isoAlpha3: 'ALB',
  },
  {
    countryCode: 'DZ',
    labelKey: 'countriesList.dz',
    isoAlpha3: 'DZA',
  },
  {
    countryCode: 'AS',
    labelKey: 'countriesList.as',
    isoAlpha3: 'ASM',
  },
  {
    countryCode: 'AD',
    labelKey: 'countriesList.ad',
    isoAlpha3: 'AND',
  },
  {
    countryCode: 'AO',
    labelKey: 'countriesList.ao',
    isoAlpha3: 'AGO',
  },
  {
    countryCode: 'AI',
    labelKey: 'countriesList.ai',
    isoAlpha3: 'AIA',
  },
  {
    countryCode: 'AQ',
    labelKey: 'countriesList.aq',
    isoAlpha3: 'ATA',
  },
  {
    countryCode: 'AG',
    labelKey: 'countriesList.ag',
    isoAlpha3: 'ATG',
  },
  {
    countryCode: 'AR',
    labelKey: 'countriesList.ar',
    isoAlpha3: 'ARG',
  },
  {
    countryCode: 'AM',
    labelKey: 'countriesList.am',
    isoAlpha3: 'ARM',
  },
  {
    countryCode: 'AW',
    labelKey: 'countriesList.aw',
    isoAlpha3: 'ABW',
  },
  {
    countryCode: 'AU',
    labelKey: 'countriesList.au',
    isoAlpha3: 'AUS',
  },
  {
    countryCode: 'AT',
    labelKey: 'countriesList.at',
    isoAlpha3: 'AUT',
  },
  {
    countryCode: 'AZ',
    labelKey: 'countriesList.az',
    isoAlpha3: 'AZE',
  },
  {
    countryCode: 'BS',
    labelKey: 'countriesList.bs',
    isoAlpha3: 'BHS',
  },
  {
    countryCode: 'BH',
    labelKey: 'countriesList.bh',
    isoAlpha3: 'BHR',
  },
  {
    countryCode: 'BD',
    labelKey: 'countriesList.bd',
    isoAlpha3: 'BGD',
  },
  {
    countryCode: 'BB',
    labelKey: 'countriesList.bb',
    isoAlpha3: 'BRB',
  },
  {
    countryCode: 'BY',
    labelKey: 'countriesList.by',
    isoAlpha3: 'BLR',
  },
  {
    countryCode: 'BE',
    labelKey: 'countriesList.be',
    isoAlpha3: 'BEL',
  },
  {
    countryCode: 'BZ',
    labelKey: 'countriesList.bz',
    isoAlpha3: 'BLZ',
  },
  {
    countryCode: 'BJ',
    labelKey: 'countriesList.bj',
    isoAlpha3: 'BEN',
  },
  {
    countryCode: 'BM',
    labelKey: 'countriesList.bm',
    isoAlpha3: 'BMU',
  },
  {
    countryCode: 'BT',
    labelKey: 'countriesList.bt',
    isoAlpha3: 'BTN',
  },
  {
    countryCode: 'BO',
    labelKey: 'countriesList.bo',
    isoAlpha3: 'BOL',
  },
  {
    countryCode: 'BQ',
    labelKey: 'countriesList.bq',
    isoAlpha3: 'BES',
  },
  {
    countryCode: 'BA',
    labelKey: 'countriesList.ba',
    isoAlpha3: 'BIH',
  },
  {
    countryCode: 'BW',
    labelKey: 'countriesList.bw',
    isoAlpha3: 'BWA',
  },
  {
    countryCode: 'BV',
    labelKey: 'countriesList.bv',
    isoAlpha3: 'BVT',
  },
  {
    countryCode: 'BR',
    labelKey: 'countriesList.br',
    isoAlpha3: 'BRA',
  },
  {
    countryCode: 'IO',
    labelKey: 'countriesList.io',
    isoAlpha3: 'IOT',
  },
  {
    countryCode: 'VG',
    labelKey: 'countriesList.vg',
    isoAlpha3: 'VGB',
  },
  {
    countryCode: 'BN',
    labelKey: 'countriesList.bn',
    isoAlpha3: 'BRN',
  },
  {
    countryCode: 'BG',
    labelKey: 'countriesList.bg',
    isoAlpha3: 'BGR',
  },
  {
    countryCode: 'BF',
    labelKey: 'countriesList.bf',
    isoAlpha3: 'BFA',
  },
  {
    countryCode: 'BI',
    labelKey: 'countriesList.bi',
    isoAlpha3: 'BDI',
  },
  {
    countryCode: 'KH',
    labelKey: 'countriesList.kh',
    isoAlpha3: 'KHM',
  },
  {
    countryCode: 'CM',
    labelKey: 'countriesList.cm',
    isoAlpha3: 'CMR',
  },
  {
    countryCode: 'CA',
    labelKey: 'countriesList.ca',
    isoAlpha3: 'CAN',
  },
  {
    countryCode: 'CV',
    labelKey: 'countriesList.cv',
    isoAlpha3: 'CPV',
  },
  {
    countryCode: 'KY',
    labelKey: 'countriesList.ky',
    isoAlpha3: 'CYM',
  },
  {
    countryCode: 'CF',
    labelKey: 'countriesList.cf',
    isoAlpha3: 'CAF',
  },
  {
    countryCode: 'TD',
    labelKey: 'countriesList.td',
    isoAlpha3: 'TCD',
  },
  {
    countryCode: 'CL',
    labelKey: 'countriesList.cl',
    isoAlpha3: 'CHL',
  },
  {
    countryCode: 'CN',
    labelKey: 'countriesList.cn',
    isoAlpha3: 'CHN',
  },
  {
    countryCode: 'CX',
    labelKey: 'countriesList.cx',
    isoAlpha3: 'CXR',
  },
  {
    countryCode: 'CC',
    labelKey: 'countriesList.cc',
    isoAlpha3: 'CCK',
  },
  {
    countryCode: 'CO',
    labelKey: 'countriesList.co',
    isoAlpha3: 'COL',
  },
  {
    countryCode: 'KM',
    labelKey: 'countriesList.km',
    isoAlpha3: 'COM',
  },
  {
    countryCode: 'CK',
    labelKey: 'countriesList.ck',
    isoAlpha3: 'COK',
  },
  {
    countryCode: 'CR',
    labelKey: 'countriesList.cr',
    isoAlpha3: 'CRI',
  },
  {
    countryCode: 'HR',
    labelKey: 'countriesList.hr',
    isoAlpha3: 'HRV',
  },
  {
    countryCode: 'CU',
    labelKey: 'countriesList.cu',
    isoAlpha3: 'CUB',
  },
  {
    countryCode: 'CW',
    labelKey: 'countriesList.cw',
    isoAlpha3: 'CUW',
  },
  {
    countryCode: 'CY',
    labelKey: 'countriesList.cy',
    isoAlpha3: 'CYP',
  },
  {
    countryCode: 'CZ',
    labelKey: 'countriesList.cz',
    isoAlpha3: 'CZE',
  },
  {
    countryCode: 'CD',
    labelKey: 'countriesList.cd',
    isoAlpha3: 'COD',
  },
  {
    countryCode: 'DK',
    labelKey: 'countriesList.dk',
    isoAlpha3: 'DNK',
  },
  {
    countryCode: 'DJ',
    labelKey: 'countriesList.dj',
    isoAlpha3: 'DJI',
  },
  {
    countryCode: 'DM',
    labelKey: 'countriesList.dm',
    isoAlpha3: 'DMA',
  },
  {
    countryCode: 'DO',
    labelKey: 'countriesList.do',
    isoAlpha3: 'DOM',
  },
  {
    countryCode: 'TL',
    labelKey: 'countriesList.tl',
    isoAlpha3: 'TLS',
  },
  {
    countryCode: 'EC',
    labelKey: 'countriesList.ec',
    isoAlpha3: 'ECU',
  },
  {
    countryCode: 'EG',
    labelKey: 'countriesList.eg',
    isoAlpha3: 'EGY',
  },
  {
    countryCode: 'SV',
    labelKey: 'countriesList.sv',
    isoAlpha3: 'SLV',
  },
  {
    countryCode: 'GQ',
    labelKey: 'countriesList.gq',
    isoAlpha3: 'GNQ',
  },
  {
    countryCode: 'ER',
    labelKey: 'countriesList.er',
    isoAlpha3: 'ERI',
  },
  {
    countryCode: 'EE',
    labelKey: 'countriesList.ee',
    isoAlpha3: 'EST',
  },
  {
    countryCode: 'ET',
    labelKey: 'countriesList.et',
    isoAlpha3: 'ETH',
  },
  {
    countryCode: 'FK',
    labelKey: 'countriesList.fk',
    isoAlpha3: 'FLK',
  },
  {
    countryCode: 'FO',
    labelKey: 'countriesList.fo',
    isoAlpha3: 'FRO',
  },
  {
    countryCode: 'FJ',
    labelKey: 'countriesList.fj',
    isoAlpha3: 'FJI',
  },
  {
    countryCode: 'FI',
    labelKey: 'countriesList.fi',
    isoAlpha3: 'FIN',
  },
  {
    countryCode: 'FR',
    labelKey: 'countriesList.fr',
    isoAlpha3: 'FRA',
  },
  {
    countryCode: 'GF',
    labelKey: 'countriesList.gf',
    isoAlpha3: 'GUF',
  },
  {
    countryCode: 'PF',
    labelKey: 'countriesList.pf',
    isoAlpha3: 'PYF',
  },
  {
    countryCode: 'TF',
    labelKey: 'countriesList.tf',
    isoAlpha3: 'ATF',
  },
  {
    countryCode: 'GA',
    labelKey: 'countriesList.ga',
    isoAlpha3: 'GAB',
  },
  {
    countryCode: 'GM',
    labelKey: 'countriesList.gm',
    isoAlpha3: 'GMB',
  },
  {
    countryCode: 'GE',
    labelKey: 'countriesList.ge',
    isoAlpha3: 'GEO',
  },
  {
    countryCode: 'DE',
    labelKey: 'countriesList.de',
    isoAlpha3: 'DEU',
  },
  {
    countryCode: 'GH',
    labelKey: 'countriesList.gh',
    isoAlpha3: 'GHA',
  },
  {
    countryCode: 'GI',
    labelKey: 'countriesList.gi',
    isoAlpha3: 'GIB',
  },
  {
    countryCode: 'GR',
    labelKey: 'countriesList.gr',
    isoAlpha3: 'GRC',
  },
  {
    countryCode: 'GL',
    labelKey: 'countriesList.gl',
    isoAlpha3: 'GRL',
  },
  {
    countryCode: 'GD',
    labelKey: 'countriesList.gd',
    isoAlpha3: 'GRD',
  },
  {
    countryCode: 'GP',
    labelKey: 'countriesList.gp',
    isoAlpha3: 'GLP',
  },
  {
    countryCode: 'GU',
    labelKey: 'countriesList.gu',
    isoAlpha3: 'GUM',
  },
  {
    countryCode: 'GT',
    labelKey: 'countriesList.gt',
    isoAlpha3: 'GTM',
  },
  {
    countryCode: 'GG',
    labelKey: 'countriesList.gg',
    isoAlpha3: 'GGY',
  },
  {
    countryCode: 'GN',
    labelKey: 'countriesList.gn',
    isoAlpha3: 'GIN',
  },
  {
    countryCode: 'GW',
    labelKey: 'countriesList.gw',
    isoAlpha3: 'GNB',
  },
  {
    countryCode: 'GY',
    labelKey: 'countriesList.gy',
    isoAlpha3: 'GUY',
  },
  {
    countryCode: 'HT',
    labelKey: 'countriesList.ht',
    isoAlpha3: 'HTI',
  },
  {
    countryCode: 'HM',
    labelKey: 'countriesList.hm',
    isoAlpha3: 'HMD',
  },
  {
    countryCode: 'HN',
    labelKey: 'countriesList.hn',
    isoAlpha3: 'HND',
  },
  {
    countryCode: 'HK',
    labelKey: 'countriesList.hk',
    isoAlpha3: 'HKG',
  },
  {
    countryCode: 'HU',
    labelKey: 'countriesList.hu',
    isoAlpha3: 'HUN',
  },
  {
    countryCode: 'IS',
    labelKey: 'countriesList.is',
    isoAlpha3: 'ISL',
  },
  {
    countryCode: 'IN',
    labelKey: 'countriesList.in',
    isoAlpha3: 'IND',
  },
  {
    countryCode: 'ID',
    labelKey: 'countriesList.id',
    isoAlpha3: 'IDN',
  },
  {
    countryCode: 'IR',
    labelKey: 'countriesList.ir',
    isoAlpha3: 'IRN',
  },
  {
    countryCode: 'IQ',
    labelKey: 'countriesList.iq',
    isoAlpha3: 'IRQ',
  },
  {
    countryCode: 'IE',
    labelKey: 'countriesList.ie',
    isoAlpha3: 'IRL',
  },
  {
    countryCode: 'IM',
    labelKey: 'countriesList.im',
    isoAlpha3: 'IMN',
  },
  {
    countryCode: 'IL',
    labelKey: 'countriesList.il',
    isoAlpha3: 'ISR',
  },
  {
    countryCode: 'IT',
    labelKey: 'countriesList.it',
    isoAlpha3: 'ITA',
  },
  {
    countryCode: 'CI',
    labelKey: 'countriesList.ci',
    isoAlpha3: 'CIV',
  },
  {
    countryCode: 'JM',
    labelKey: 'countriesList.jm',
    isoAlpha3: 'JAM',
  },
  {
    countryCode: 'JP',
    labelKey: 'countriesList.jp',
    isoAlpha3: 'JPN',
  },
  {
    countryCode: 'JE',
    labelKey: 'countriesList.je',
    isoAlpha3: 'JEY',
  },
  {
    countryCode: 'JO',
    labelKey: 'countriesList.jo',
    isoAlpha3: 'JOR',
  },
  {
    countryCode: 'KZ',
    labelKey: 'countriesList.kz',
    isoAlpha3: 'KAZ',
  },
  {
    countryCode: 'KE',
    labelKey: 'countriesList.ke',
    isoAlpha3: 'KEN',
  },
  {
    countryCode: 'KI',
    labelKey: 'countriesList.ki',
    isoAlpha3: 'KIR',
  },
  {
    countryCode: 'XK',
    labelKey: 'countriesList.xk',
    isoAlpha3: 'XKX',
  },
  {
    countryCode: 'KW',
    labelKey: 'countriesList.kw',
    isoAlpha3: 'KWT',
  },
  {
    countryCode: 'KG',
    labelKey: 'countriesList.kg',
    isoAlpha3: 'KGZ',
  },
  {
    countryCode: 'LA',
    labelKey: 'countriesList.la',
    isoAlpha3: 'LAO',
  },
  {
    countryCode: 'LV',
    labelKey: 'countriesList.lv',
    isoAlpha3: 'LVA',
  },
  {
    countryCode: 'LB',
    labelKey: 'countriesList.lb',
    isoAlpha3: 'LBN',
  },
  {
    countryCode: 'LS',
    labelKey: 'countriesList.ls',
    isoAlpha3: 'LSO',
  },
  {
    countryCode: 'LR',
    labelKey: 'countriesList.lr',
    isoAlpha3: 'LBR',
  },
  {
    countryCode: 'LY',
    labelKey: 'countriesList.ly',
    isoAlpha3: 'LBY',
  },
  {
    countryCode: 'LI',
    labelKey: 'countriesList.li',
    isoAlpha3: 'LIE',
  },
  {
    countryCode: 'LT',
    labelKey: 'countriesList.lt',
    isoAlpha3: 'LTU',
  },
  {
    countryCode: 'LU',
    labelKey: 'countriesList.lu',
    isoAlpha3: 'LUX',
  },
  {
    countryCode: 'MO',
    labelKey: 'countriesList.mo',
    isoAlpha3: 'MAC',
  },
  {
    countryCode: 'MK',
    labelKey: 'countriesList.mk',
    isoAlpha3: 'MKD',
  },
  {
    countryCode: 'MG',
    labelKey: 'countriesList.mg',
    isoAlpha3: 'MDG',
  },
  {
    countryCode: 'MW',
    labelKey: 'countriesList.mw',
    isoAlpha3: 'MWI',
  },
  {
    countryCode: 'MY',
    labelKey: 'countriesList.my',
    isoAlpha3: 'MYS',
  },
  {
    countryCode: 'MV',
    labelKey: 'countriesList.mv',
    isoAlpha3: 'MDV',
  },
  {
    countryCode: 'ML',
    labelKey: 'countriesList.ml',
    isoAlpha3: 'MLI',
  },
  {
    countryCode: 'MT',
    labelKey: 'countriesList.mt',
    isoAlpha3: 'MLT',
  },
  {
    countryCode: 'MH',
    labelKey: 'countriesList.mh',
    isoAlpha3: 'MHL',
  },
  {
    countryCode: 'MQ',
    labelKey: 'countriesList.mq',
    isoAlpha3: 'MTQ',
  },
  {
    countryCode: 'MR',
    labelKey: 'countriesList.mr',
    isoAlpha3: 'MRT',
  },
  {
    countryCode: 'MU',
    labelKey: 'countriesList.mu',
    isoAlpha3: 'MUS',
  },
  {
    countryCode: 'YT',
    labelKey: 'countriesList.yt',
    isoAlpha3: 'MYT',
  },
  {
    countryCode: 'MX',
    labelKey: 'countriesList.mx',
    isoAlpha3: 'MEX',
  },
  {
    countryCode: 'FM',
    labelKey: 'countriesList.fm',
    isoAlpha3: 'FSM',
  },
  {
    countryCode: 'MD',
    labelKey: 'countriesList.md',
    isoAlpha3: 'MDA',
  },
  {
    countryCode: 'MC',
    labelKey: 'countriesList.mc',
    isoAlpha3: 'MCO',
  },
  {
    countryCode: 'MN',
    labelKey: 'countriesList.mn',
    isoAlpha3: 'MNG',
  },
  {
    countryCode: 'ME',
    labelKey: 'countriesList.me',
    isoAlpha3: 'MNE',
  },
  {
    countryCode: 'MS',
    labelKey: 'countriesList.ms',
    isoAlpha3: 'MSR',
  },
  {
    countryCode: 'MA',
    labelKey: 'countriesList.ma',
    isoAlpha3: 'MAR',
  },
  {
    countryCode: 'MZ',
    labelKey: 'countriesList.mz',
    isoAlpha3: 'MOZ',
  },
  {
    countryCode: 'MM',
    labelKey: 'countriesList.mm',
    isoAlpha3: 'MMR',
  },
  {
    countryCode: 'NA',
    labelKey: 'countriesList.na',
    isoAlpha3: 'NAM',
  },
  {
    countryCode: 'NR',
    labelKey: 'countriesList.nr',
    isoAlpha3: 'NRU',
  },
  {
    countryCode: 'NP',
    labelKey: 'countriesList.np',
    isoAlpha3: 'NPL',
  },
  {
    countryCode: 'NL',
    labelKey: 'countriesList.nl',
    isoAlpha3: 'NLD',
  },
  {
    countryCode: 'NC',
    labelKey: 'countriesList.nc',
    isoAlpha3: 'NCL',
  },
  {
    countryCode: 'NZ',
    labelKey: 'countriesList.nz',
    isoAlpha3: 'NZL',
  },
  {
    countryCode: 'NI',
    labelKey: 'countriesList.ni',
    isoAlpha3: 'NIC',
  },
  {
    countryCode: 'NE',
    labelKey: 'countriesList.ne',
    isoAlpha3: 'NER',
  },
  {
    countryCode: 'NG',
    labelKey: 'countriesList.ng',
    isoAlpha3: 'NGA',
  },
  {
    countryCode: 'NU',
    labelKey: 'countriesList.nu',
    isoAlpha3: 'NIU',
  },
  {
    countryCode: 'NF',
    labelKey: 'countriesList.nf',
    isoAlpha3: 'NFK',
  },
  {
    countryCode: 'KP',
    labelKey: 'countriesList.kp',
    isoAlpha3: 'PRK',
  },
  {
    countryCode: 'MP',
    labelKey: 'countriesList.mp',
    isoAlpha3: 'MNP',
  },
  {
    countryCode: 'NO',
    labelKey: 'countriesList.no',
    isoAlpha3: 'NOR',
  },
  {
    countryCode: 'OM',
    labelKey: 'countriesList.om',
    isoAlpha3: 'OMN',
  },
  {
    countryCode: 'PK',
    labelKey: 'countriesList.pk',
    isoAlpha3: 'PAK',
  },
  {
    countryCode: 'PW',
    labelKey: 'countriesList.pw',
    isoAlpha3: 'PLW',
  },
  {
    countryCode: 'PS',
    labelKey: 'countriesList.ps',
    isoAlpha3: 'PSE',
  },
  {
    countryCode: 'PA',
    labelKey: 'countriesList.pa',
    isoAlpha3: 'PAN',
  },
  {
    countryCode: 'PG',
    labelKey: 'countriesList.pg',
    isoAlpha3: 'PNG',
  },
  {
    countryCode: 'PY',
    labelKey: 'countriesList.py',
    isoAlpha3: 'PRY',
  },
  {
    countryCode: 'PE',
    labelKey: 'countriesList.pe',
    isoAlpha3: 'PER',
  },
  {
    countryCode: 'PH',
    labelKey: 'countriesList.ph',
    isoAlpha3: 'PHL',
  },
  {
    countryCode: 'PN',
    labelKey: 'countriesList.pn',
    isoAlpha3: 'PCN',
  },
  {
    countryCode: 'PL',
    labelKey: 'countriesList.pl',
    isoAlpha3: 'POL',
  },
  {
    countryCode: 'PT',
    labelKey: 'countriesList.pt',
    isoAlpha3: 'PRT',
  },
  {
    countryCode: 'PR',
    labelKey: 'countriesList.pr',
    isoAlpha3: 'PRI',
  },
  {
    countryCode: 'QA',
    labelKey: 'countriesList.qa',
    isoAlpha3: 'QAT',
  },
  {
    countryCode: 'CG',
    labelKey: 'countriesList.cg',
    isoAlpha3: 'COG',
  },
  {
    countryCode: 'RO',
    labelKey: 'countriesList.ro',
    isoAlpha3: 'ROU',
  },
  {
    countryCode: 'RU',
    labelKey: 'countriesList.ru',
    isoAlpha3: 'RUS',
  },
  {
    countryCode: 'RW',
    labelKey: 'countriesList.rw',
    isoAlpha3: 'RWA',
  },
  {
    countryCode: 'RE',
    labelKey: 'countriesList.re',
    isoAlpha3: 'REU',
  },
  {
    countryCode: 'BL',
    labelKey: 'countriesList.bl',
    isoAlpha3: 'BLM',
  },
  {
    countryCode: 'SH',
    labelKey: 'countriesList.sh',
    isoAlpha3: 'SHN',
  },
  {
    countryCode: 'KN',
    labelKey: 'countriesList.kn',
    isoAlpha3: 'KNA',
  },
  {
    countryCode: 'LC',
    labelKey: 'countriesList.lc',
    isoAlpha3: 'LCA',
  },
  {
    countryCode: 'MF',
    labelKey: 'countriesList.mf',
    isoAlpha3: 'MAF',
  },
  {
    countryCode: 'PM',
    labelKey: 'countriesList.pm',
    isoAlpha3: 'SPM',
  },
  {
    countryCode: 'VC',
    labelKey: 'countriesList.vc',
    isoAlpha3: 'VCT',
  },
  {
    countryCode: 'WS',
    labelKey: 'countriesList.ws',
    isoAlpha3: 'WSM',
  },
  {
    countryCode: 'SM',
    labelKey: 'countriesList.sm',
    isoAlpha3: 'SMR',
  },
  {
    countryCode: 'SA',
    labelKey: 'countriesList.sa',
    isoAlpha3: 'SAU',
  },
  {
    countryCode: 'SN',
    labelKey: 'countriesList.sn',
    isoAlpha3: 'SEN',
  },
  {
    countryCode: 'RS',
    labelKey: 'countriesList.rs',
    isoAlpha3: 'SRB',
  },
  {
    countryCode: 'SC',
    labelKey: 'countriesList.sc',
    isoAlpha3: 'SYC',
  },
  {
    countryCode: 'SL',
    labelKey: 'countriesList.sl',
    isoAlpha3: 'SLE',
  },
  {
    countryCode: 'SG',
    labelKey: 'countriesList.sg',
    isoAlpha3: 'SGP',
  },
  {
    countryCode: 'SX',
    labelKey: 'countriesList.sx',
    isoAlpha3: 'SXM',
  },
  {
    countryCode: 'SK',
    labelKey: 'countriesList.sk',
    isoAlpha3: 'SVK',
  },
  {
    countryCode: 'SI',
    labelKey: 'countriesList.si',
    isoAlpha3: 'SVN',
  },
  {
    countryCode: 'SB',
    labelKey: 'countriesList.sb',
    isoAlpha3: 'SLB',
  },
  {
    countryCode: 'SO',
    labelKey: 'countriesList.so',
    isoAlpha3: 'SOM',
  },
  {
    countryCode: 'ZA',
    labelKey: 'countriesList.za',
    isoAlpha3: 'ZAF',
  },
  {
    countryCode: 'GS',
    labelKey: 'countriesList.gs',
    isoAlpha3: 'SGS',
  },
  {
    countryCode: 'KR',
    labelKey: 'countriesList.kr',
    isoAlpha3: 'KOR',
  },
  {
    countryCode: 'SS',
    labelKey: 'countriesList.ss',
    isoAlpha3: 'SSD',
  },
  {
    countryCode: 'ES',
    labelKey: 'countriesList.es',
    isoAlpha3: 'ESP',
  },
  {
    countryCode: 'LK',
    labelKey: 'countriesList.lk',
    isoAlpha3: 'LKA',
  },
  {
    countryCode: 'SD',
    labelKey: 'countriesList.sd',
    isoAlpha3: 'SDN',
  },
  {
    countryCode: 'SR',
    labelKey: 'countriesList.sr',
    isoAlpha3: 'SUR',
  },
  {
    countryCode: 'SJ',
    labelKey: 'countriesList.sj',
    isoAlpha3: 'SJM',
  },
  {
    countryCode: 'SZ',
    labelKey: 'countriesList.sz',
    isoAlpha3: 'SWZ',
  },
  {
    countryCode: 'SE',
    labelKey: 'countriesList.se',
    isoAlpha3: 'SWE',
  },
  {
    countryCode: 'CH',
    labelKey: 'countriesList.ch',
    isoAlpha3: 'CHE',
  },
  {
    countryCode: 'SY',
    labelKey: 'countriesList.sy',
    isoAlpha3: 'SYR',
  },
  {
    countryCode: 'ST',
    labelKey: 'countriesList.st',
    isoAlpha3: 'STP',
  },
  {
    countryCode: 'TW',
    labelKey: 'countriesList.tw',
    isoAlpha3: 'TWN',
  },
  {
    countryCode: 'TJ',
    labelKey: 'countriesList.tj',
    isoAlpha3: 'TJK',
  },
  {
    countryCode: 'TZ',
    labelKey: 'countriesList.tz',
    isoAlpha3: 'TZA',
  },
  {
    countryCode: 'TH',
    labelKey: 'countriesList.th',
    isoAlpha3: 'THA',
  },
  {
    countryCode: 'TG',
    labelKey: 'countriesList.tg',
    isoAlpha3: 'TGO',
  },
  {
    countryCode: 'TK',
    labelKey: 'countriesList.tk',
    isoAlpha3: 'TKL',
  },
  {
    countryCode: 'TO',
    labelKey: 'countriesList.to',
    isoAlpha3: 'TON',
  },
  {
    countryCode: 'TT',
    labelKey: 'countriesList.tt',
    isoAlpha3: 'TTO',
  },
  {
    countryCode: 'TN',
    labelKey: 'countriesList.tn',
    isoAlpha3: 'TUN',
  },
  {
    countryCode: 'TR',
    labelKey: 'countriesList.tr',
    isoAlpha3: 'TUR',
  },
  {
    countryCode: 'TM',
    labelKey: 'countriesList.tm',
    isoAlpha3: 'TKM',
  },
  {
    countryCode: 'TC',
    labelKey: 'countriesList.tc',
    isoAlpha3: 'TCA',
  },
  {
    countryCode: 'TV',
    labelKey: 'countriesList.tv',
    isoAlpha3: 'TUV',
  },
  {
    countryCode: 'UM',
    labelKey: 'countriesList.um',
    isoAlpha3: 'UMI',
  },
  {
    countryCode: 'VI',
    labelKey: 'countriesList.vi',
    isoAlpha3: 'VIR',
  },
  {
    countryCode: 'UG',
    labelKey: 'countriesList.ug',
    isoAlpha3: 'UGA',
  },
  {
    countryCode: 'UA',
    labelKey: 'countriesList.ua',
    isoAlpha3: 'UKR',
  },
  {
    countryCode: 'AE',
    labelKey: 'countriesList.ae',
    isoAlpha3: 'ARE',
  },
  {
    countryCode: 'GB',
    labelKey: 'countriesList.gb',
    isoAlpha3: 'GBR',
  },
  {
    countryCode: 'US',
    labelKey: 'countriesList.us',
    isoAlpha3: 'USA',
  },
  {
    countryCode: 'UY',
    labelKey: 'countriesList.uy',
    isoAlpha3: 'URY',
  },
  {
    countryCode: 'UZ',
    labelKey: 'countriesList.uz',
    isoAlpha3: 'UZB',
  },
  {
    countryCode: 'VU',
    labelKey: 'countriesList.vu',
    isoAlpha3: 'VUT',
  },
  {
    countryCode: 'VA',
    labelKey: 'countriesList.va',
    isoAlpha3: 'VAT',
  },
  {
    countryCode: 'VE',
    labelKey: 'countriesList.ve',
    isoAlpha3: 'VEN',
  },
  {
    countryCode: 'VN',
    labelKey: 'countriesList.vn',
    isoAlpha3: 'VNM',
  },
  {
    countryCode: 'WF',
    labelKey: 'countriesList.wf',
    isoAlpha3: 'WLF',
  },
  {
    countryCode: 'EH',
    labelKey: 'countriesList.eh',
    isoAlpha3: 'ESH',
  },
  {
    countryCode: 'YE',
    labelKey: 'countriesList.ye',
    isoAlpha3: 'YEM',
  },
  {
    countryCode: 'ZM',
    labelKey: 'countriesList.zm',
    isoAlpha3: 'ZMB',
  },
  {
    countryCode: 'ZW',
    labelKey: 'countriesList.zw',
    isoAlpha3: 'ZWE',
  },
  {
    countryCode: 'AX',
    labelKey: 'countriesList.ax',
    isoAlpha3: 'ALA',
  },
]

export const countryTranslations = {
  af: 'Afghanistan',
  al: 'Albania',
  dz: 'Algeria',
  as: 'American Samoa',
  ad: 'Andorra',
  ao: 'Angola',
  ai: 'Anguilla',
  aq: 'Antarctica',
  ag: 'Antigua and Barbuda',
  ar: 'Argentina',
  am: 'Armenia',
  aw: 'Aruba',
  au: 'Australia',
  at: 'Austria',
  az: 'Azerbaijan',
  bs: 'Bahamas',
  bh: 'Bahrain',
  bd: 'Bangladesh',
  bb: 'Barbados',
  by: 'Belarus',
  be: 'Belgium',
  bz: 'Belize',
  bj: 'Benin',
  bm: 'Bermuda',
  bt: 'Bhutan',
  bo: 'Bolivia',
  bq: 'Bonaire',
  ba: 'Bosnia and Herzegovina',
  bw: 'Botswana',
  bv: 'Bouvet Island',
  br: 'Brazil',
  io: 'British Indian Ocean Territory',
  vg: 'British Virgin Islands',
  bn: 'Brunei',
  bg: 'Bulgaria',
  bf: 'Burkina Faso',
  bi: 'Burundi',
  kh: 'Cambodia',
  cm: 'Cameroon',
  ca: 'Canada',
  cv: 'Cape Verde',
  ky: 'Cayman Islands',
  cf: 'Central African Republic',
  td: 'Chad',
  cl: 'Chile',
  cn: 'China',
  cx: 'Christmas Island',
  cc: 'Cocos [Keeling] Islands',
  co: 'Colombia',
  km: 'Comoros',
  ck: 'Cook Islands',
  cr: 'Costa Rica',
  hr: 'Croatia',
  cu: 'Cuba',
  cw: 'Curacao',
  cy: 'Cyprus',
  cz: 'Czechia',
  cd: 'Democratic Republic of the Congo',
  dk: 'Denmark',
  dj: 'Djibouti',
  dm: 'Dominica',
  do: 'Dominican Republic',
  tl: 'East Timor',
  ec: 'Ecuador',
  eg: 'Egypt',
  sv: 'El Salvador',
  gq: 'Equatorial Guinea',
  er: 'Eritrea',
  ee: 'Estonia',
  et: 'Ethiopia',
  fk: 'Falkland Islands',
  fo: 'Faroe Islands',
  fj: 'Fiji',
  fi: 'Finland',
  fr: 'France',
  gf: 'French Guiana',
  pf: 'French Polynesia',
  tf: 'French Southern Territories',
  ga: 'Gabon',
  gm: 'Gambia',
  ge: 'Georgia',
  de: 'Germany',
  gh: 'Ghana',
  gi: 'Gibraltar',
  gr: 'Greece',
  gl: 'Greenland',
  gd: 'Grenada',
  gp: 'Guadeloupe',
  gu: 'Guam',
  gt: 'Guatemala',
  gg: 'Guernsey',
  gn: 'Guinea',
  gw: 'Guinea-Bissau',
  gy: 'Guyana',
  ht: 'Haiti',
  hm: 'Heard Island and McDonald Islands',
  hn: 'Honduras',
  hk: 'Hong Kong',
  hu: 'Hungary',
  is: 'Iceland',
  in: 'India',
  id: 'Indonesia',
  ir: 'Iran',
  iq: 'Iraq',
  ie: 'Ireland',
  im: 'Isle of Man',
  il: 'Israel',
  it: 'Italy',
  ci: 'Ivory Coast',
  jm: 'Jamaica',
  jp: 'Japan',
  je: 'Jersey',
  jo: 'Jordan',
  kz: 'Kazakhstan',
  ke: 'Kenya',
  ki: 'Kiribati',
  xk: 'Kosovo',
  kw: 'Kuwait',
  kg: 'Kyrgyzstan',
  la: 'Laos',
  lv: 'Latvia',
  lb: 'Lebanon',
  ls: 'Lesotho',
  lr: 'Liberia',
  ly: 'Libya',
  li: 'Liechtenstein',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  mo: 'Macao',
  mk: 'Macedonia',
  mg: 'Madagascar',
  mw: 'Malawi',
  my: 'Malaysia',
  mv: 'Maldives',
  ml: 'Mali',
  mt: 'Malta',
  mh: 'Marshall Islands',
  mq: 'Martinique',
  mr: 'Mauritania',
  mu: 'Mauritius',
  yt: 'Mayotte',
  mx: 'Mexico',
  fm: 'Micronesia',
  md: 'Moldova',
  mc: 'Monaco',
  mn: 'Mongolia',
  me: 'Montenegro',
  ms: 'Montserrat',
  ma: 'Morocco',
  mz: 'Mozambique',
  mm: 'Myanmar [Burma]',
  na: 'Namibia',
  nr: 'Nauru',
  np: 'Nepal',
  nl: 'Netherlands',
  nc: 'New Caledonia',
  nz: 'New Zealand',
  ni: 'Nicaragua',
  ne: 'Niger',
  ng: 'Nigeria',
  nu: 'Niue',
  nf: 'Norfolk Island',
  kp: 'North Korea',
  mp: 'Northern Mariana Islands',
  no: 'Norway',
  om: 'Oman',
  pk: 'Pakistan',
  pw: 'Palau',
  ps: 'Palestine',
  pa: 'Panama',
  pg: 'Papua New Guinea',
  py: 'Paraguay',
  pe: 'Peru',
  ph: 'Philippines',
  pn: 'Pitcairn Islands',
  pl: 'Poland',
  pt: 'Portugal',
  pr: 'Puerto Rico',
  qa: 'Qatar',
  cg: 'Republic of the Congo',
  ro: 'Romania',
  ru: 'Russia',
  rw: 'Rwanda',
  re: 'Réunion',
  bl: 'Saint Barthélemy',
  sh: 'Saint Helena',
  kn: 'Saint Kitts and Nevis',
  lc: 'Saint Lucia',
  mf: 'Saint Martin',
  pm: 'Saint Pierre and Miquelon',
  vc: 'Saint Vincent and the Grenadines',
  ws: 'Samoa',
  sm: 'San Marino',
  sa: 'Saudi Arabia',
  sn: 'Senegal',
  rs: 'Serbia',
  sc: 'Seychelles',
  sl: 'Sierra Leone',
  sg: 'Singapore',
  sx: 'Sint Maarten',
  sk: 'Slovakia',
  si: 'Slovenia',
  sb: 'Solomon Islands',
  so: 'Somalia',
  za: 'South Africa',
  gs: 'South Georgia and the South Sandwich Islands',
  kr: 'South Korea',
  ss: 'South Sudan',
  es: 'Spain',
  lk: 'Sri Lanka',
  sd: 'Sudan',
  sr: 'Suriname',
  sj: 'Svalbard and Jan Mayen',
  sz: 'Swaziland',
  se: 'Sweden',
  ch: 'Switzerland',
  sy: 'Syria',
  st: 'São Tomé and Príncipe',
  tw: 'Taiwan',
  tj: 'Tajikistan',
  tz: 'Tanzania',
  th: 'Thailand',
  tg: 'Togo',
  tk: 'Tokelau',
  to: 'Tonga',
  tt: 'Trinidad and Tobago',
  tn: 'Tunisia',
  tr: 'Turkey',
  tm: 'Turkmenistan',
  tc: 'Turks and Caicos Islands',
  tv: 'Tuvalu',
  um: 'U.S. Minor Outlying Islands',
  vi: 'U.S. Virgin Islands',
  ug: 'Uganda',
  ua: 'Ukraine',
  ae: 'United Arab Emirates',
  gb: 'United Kingdom',
  us: 'United States of America',
  uy: 'Uruguay',
  uz: 'Uzbekistan',
  vu: 'Vanuatu',
  va: 'Vatican City',
  ve: 'Venezuela',
  vn: 'Vietnam',
  wf: 'Wallis and Futuna',
  eh: 'Western Sahara',
  ye: 'Yemen',
  zm: 'Zambia',
  zw: 'Zimbabwe',
  ax: 'Åland',
}
