export const VIDEO_CAPTURE = {
  INACTIVE_TIMEOUT: 12,
  FACE_VIDEO_TIMEOUT: 20,
  DOC_VIDEO_TIMEOUT: 30,
}

export const DOC_VIDEO_CAPTURE = {
  BUTTON_VISIBILITY_TIMEOUT: 3000,
  CAMERA_OVERLAY_TIMEOUT: 3000,
  SUCCESS_STATE_TIMEOUT: 2000,
  SUCCESS_STATE_VIBRATION: 500,
  HOLDING_STILL_TIMEOUT: 6000,
}

export const DOC_MULTI_FRAME_CAPTURE = {
  CAPTURE_DURATION: 6000,
  SUCCESS_STATE_TIMEOUT: 2000,
}
