name: Percy Visual Regression Tests - Master

on:
  push:
    branches:
      - master
      - development

jobs:
  percy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

        # Needed to be able to run `npm ci`. It fails if we try to install libraries from a github repo
        # e.g. "wpt": "git+https://github.com/Woopra/browser-tracker.git#v5.1.20",
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Build test server
        run: npm run build:test
        id: testserver

      - name: Install Percy
        run: npm install -g @percy/cli

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: actions/checkout@v2
        with:
          repository: it-ony/webtest
          path: webtest

      - name: Build webtest
        run: cd webtest && mvn --no-transfer-progress clean install && cd ..

      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v1

      - name: Run percy tests in Chrome
        working-directory: ./test/webtest
        id: chrome
        run: ./run-ui-tests.sh "-Dbrowser=chrome -Dgroups=percy -DthreadCount=10 -Denvironment=headless"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_JAVA }}
